# Site
repository: mvdemecillo/resume
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Ma. Victoria Demecillo
title: Remote Desktop Engineer
email: mvdemecillo@gmail.com
phone: +63 917 906 7942
website: https://mvdemecillo.github.io/resume/

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  mvdemecillo
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: mv-demecillo-663a59194
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I am Ma. Victoria and I'm a remote desktop engineer. I work as a remote technical assistant and service operations support, acting as an escalation from other support teams.

  I am well versed with <mark>Exchange</mark>, <mark>Networking</mark>, <mark>Storage</mark>, <mark>Desktop Management Windows 7 and 10</mark>, <mark>Active Directory</mark>, <mark>Azure AD</mark>, <mark>Citrix</mark>

content:
  - title: Technical Skills # Title for the section
    layout: text # Type of content section (list/text)
    content: |
      - Email Administration: <mark>Microsoft Exchange 2010</mark>, <mark>Microsoft Exchange 2013</mark> and <mark>Exchange Online</mark>
      - <mark>Office 365</mark> / <mark>O365 Admin Center</mark> - Setting up O365 account from scratch  
      - <mark>Active Directory</mark>, <mark>Azure AD</mark> management 
      - <mark>IBM Notes</mark>, <mark>Lotus Notes</mark> 
      - <mark>Lync</mark>, <mark>Skype for Business</mark>, <mark>Microsoft Teams</mark> 
      - Desktop related and corporate applications troubleshooting 
      - Virtual Machines management: <mark>Citrix Studio</mark> 
      - Ticketing Tools: <mark>ITSM Maximo</mark>, <mark>BMC Remedy</mark>, <mark>ServiceNow</mark> 
      - Mobile device support: <mark>MobileIron</mark>, <mark>Intune</mark>, <mark>BlackBerry</mark> 
      - Remote desktop tool: <mark>Skype</mark>, <mark>Dameware</mark>, <mark>TeamViewer</mark>, <mark>Bomgar</mark>, <mark>CrcViewer</mark>, <mark>LogMeIn</mark> 
      - VPN Support: <mark>Cisco AnyConnect</mark>, <mark>F5 Big IP Edge Client</mark> 
      - <mark>SCCM</mark> troubleshooting 
      - Currently taking up <mark>CompTIA Network+</mark> with Certification  
      - Certified with <mark>Fundamentals of Workforce Management</mark>
    

  - title: Experiences
    layout: list
    content:
      - layout: left
        border: weak 
        title: ATOS - SYNTEL
        link: https://atos.net/en/
        link_text: atos.net
        sub_title: Remote Desktop Engineer / Remote Technical Assistant / Service Operations Support 
        caption: November 2018 - Present
        quote: >
          10th Floor, Tower 3, Science Hub, McKinley Hill, Taguig City  
        description: | # this will include new lines to allow paragraphs
            
            - Provide technical support to end users and staff on computer operation and other issues.
            - Act as local IT for the client image computers.
            - Supports remote access to Client environment.
            - Install, update, and repair software on the organization's systems and applications.
            - Resolve desktop related problems or escalate it to the respective technical support team.
            - Moved eventually to RTA team, served as second line support for Service Desk Analysts.
            - Intermediate to advanced solution support for Exchange, Networking, Storage, Desktop Management Windows 7 and 10, Active Directory, Azure AD and Citrix.
            - Serve as an escalation/immediate support for front-line agents when the issue requires intermediate to advanced troubleshooting
            - Help in the knowledge management for Service Desk; create / update knowledge articles.
            - Ensure quality actioning of service requests and workflow management e.g. ticket - creation/triage/classification/prioritation/assignment/actioning/resolution/closure.
            - Liaise closely with other cross-functional tier support teams.
            - Support for core Client applications.
            - Performs account administration (creations and terminations).
            - Moved eventually to SOS team
            - Addresses all conflicts, challenges and showstoppers by collaborating across other support teams and escalating when necessary.
            - Owns escalated Incidents from L1/RTA support teams, get daily updates from SMEs, understand the situation, escalate, if necessary, to keep the ball rolling and provide updates to the end users.
            - Provide VIP end-users support acting as their champion and owning the request or incident to completion

      - layout: left
        border: weak
        title: CGI Philippines
        link: https://www.cgi.com/philippines/en
        link_text: cgi.com
        sub_title: Service Desk Specialist / IT Security  Analyst 
        caption: July 2016 - August 2018
        quote: >
          2nd Floor, One World Square, McKinley Hill, Taguig City  
        description: |

          - Handles incident tickets with utmost carefulness depending on the level of urgency and impact on the business via phone, chat or email.
          - Handles first line incidents, including triage and troubleshooting, resolution where possible and assignment where required to 2nd/3rd line support teams and third parties.
          - Troubleshooting software problems and printer problems
          - Familiar with Active Directory, VPN Connection, Citrix Environment, IBM Notes/Lotus, MS Outlook/O365/Exchange ticketing tool such as; ITSM Maximo and BMC Remedy, remote desktop tool (Bomgar, Remote Desktop Connection, IBM BigFix Remote Controller, SCCM)
          - Troubleshoot Retail devices such as Registers, Debit Machines, Scanners, POS and Printers
          - Handles user account creation, modification and deletion thru Active Directory, Exchange, Mainframe and IBM Lotus Notes
          - Handles support for Video conferencing and SFB conferencing troubleshooting
          - 3 months after doing front liner tasks, I was assigned to handle Quality Assurance responsibilities for almost a year. Then moved to Queue Management handling ticket escalations and backlogs. I also did ADHOC tasks such as sending reports to higher opts and clients.
          - Last task given was a backup of our team's Workforce Analyst

      - layout: left
        border: weak
        title: Cognizant Philippines
        sub_title: Sr. System Engineer 
        link: https://www.cognizant.com/ph/en
        link_text: cognizant.com
        caption: October 2015 - April 2016
        quote: >
          2nd flr Tower 4, Science Hub, McKinley Hill, Taguig City 
        description: |
          - Handles mostly MS Outlook and AD account concerns.  
          - Triage for client specific applications.

      - layout: left
        border: weak
        title: Stefanini Philippines 
        link: https://stefanini.com/en/philippines
        link_text: stefanini.com
        sub_title: IT Service Desk
        caption: September 2013 - August 2014
        quote: >
          30th Floor GT Tower, Makati City
        description: |
          - Supports technical and some financial queries from Ernst and Young employees via phone, email or chat.
          - Supports Lotus Notes and Outlook users.
          - Responsible for setting up corporate emails on user's mobile phones (iPhone and Blackberry), authentication support, and desktop related concerns.
          - Handles internal/corporate application support, account administration and password resets, vpn issues for home-based users, and mobile device management.
          - After meticulously exhausting level1 troubleshooting steps, escalate tickets to the appropriate Level 2 technical group for further assistance and permanent resolution.

      - layout: left
        title: TeleTech Inc.
        sub_title: Technical Support 1
        link: https://www.ttec.com/
        link_text: www.ttec.com
        caption: Jun 2008 - June 2012
        quote: >
          4th Floor SM City, Bacoor, Cavite 
        description: |
          - Provides Level 1 technical support for HP notebook customers.  
          - Handles admin tasks for Telstra account customers. 


  - title: Education
    layout: list
    content:
      - title: Pamantasan ng Lungsod ng Muntinlupa
        layout: top-right
        sub_title: BS in Computer Science
        caption: April 2007
        description: |
          
          Bachelor's degree in Computer Science from Pamantasan ng Lungsod ng Manila, Reservation, Brgy. Poblacion, City of Muntinlupa


# Footer
footer_show_references: true
references_title: References available on request

# Build settings
remote_theme: sproogen/resume-theme

# sass:
#   style: compressed